export const sounds = [
  ["boing", "Resorte loco", "🌀"],
  ["pato", "Pato cósmico", "🦆"],
  ["robot", "Robot confundido", "🤖"],
  ["burbuja", "Burbujas", "🫧"],
  ["trombon", "Trombón triste", "🎺"],
  ["ardilla", "Ardilla veloz", "🐿️"],
  ["ovni", "Llegó el OVNI", "🛸"],
  ["rebote", "Pelota rebotona", "🏀"],
  ["hipo", "Hipo digital", "😵"],
  ["risita", "Risita robótica", "😆"],
  ["laser", "Piu piu", "🔫"],
  ["caida", "Caída de caricatura", "🙃"],
  ["moneda", "Moneda extra", "🪙"],
  ["error", "Oops", "🤦"],
  ["magia", "Magia instantánea", "🪄"],
  ["grillo", "Grillos incómodos", "🦗"],
  ["fantasma", "Fantasmita", "👻"],
  ["carrera", "Motor de juguete", "🏎️"],
  ["globo", "Globo escapando", "🎈"],
  ["victoria", "Mini victoria", "🏆"],
  ["barco", "Alarma barco", "🚢"],
  ["bocina", "Bocina de camión", "🚛"],
  ["niebla", "Sirena de niebla", "🌫️"],
  ["submarino", "Sonar submarino", "⚓"],
  ["sirena", "Sirena ascendente", "🚨"],
  ["tren", "Bocina de tren", "🚂"],
  ["puerto", "Alerta de puerto", "🛟"],
  ["claxon", "Claxon doble", "🚗"],
  ["evacuacion", "Alarma pulsante", "🔔"],
  ["remolcador", "Remolcador", "⛴️"],
].map(([id, label, emoji], i) => ({
  id,
  label,
  emoji,
  category: i < 20 ? "Diversión" : "Alarmas",
  color: ["#b5e8ca", "#fbd797", "#cebaff", "#9cdce9", "#ffb5af"][i % 5],
  index: i,
}));
export const catalog = [
  ...sounds,
  {
    id: "buzz",
    label: "Zumbido MSN",
    emoji: "📳",
    category: "Zumbido",
    color: "#b5e8ca",
  },
];
